### ISSUE TITLE
Add license for this repo

### ISSUE THREAD

**Issue by Jennifer88huang-zz** [CommunityLeadershipDevelopment/doc_guide#16]
Which license do we use for this repo?

**Comment by tanzhongyi003** [comment]
Creative Commons Zero v1.0 Universal

**Comment by tanzhongyi003** [comment]
It already has one，Creative Commons Zero v1.0 Universal

**Comment by Jennifer88huang-zz** [comment]
Thanks for your response @tanzhongyi003
